version: '3'

services:
  mobsf:
    image: opensecurity/mobile-security-framework-mobsf:latest
    environment:
      - MOBSF_API_KEY=12345
    ports:
      - 8000:8000
  
  scan:
    build:
      context: ./scan
    environment:
      - MOBSF_URL=http://mobsf:8000/
      - TARGET_PATH=${TARGET_PATH}
      - MIN_SECURITY_SCORE=${MIN_SECURITY_SCORE}
      - MAX_CVSS_SCORE=${MAX_CVSS_SCORE}

    volumes:
      - "$PWD/output:/app/output"
      - "$PWD/target:/app/target"

    depends_on:
      - mobsf
